# Generated by Django 6.0.6 on 2026-06-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
